<?php

function d7slider_menu(){
  $items = array();
  
  $items['admin/config/karbunkul'] = array(
    'title' => 'Karbunkul',
    'description' => '',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/karbunkul/d7slider'] = array(
    'title' => 'D7 slider',
    'description' => 'Slider for Drupal 7',
    'page callback' => 'page_sliders',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/config/karbunkul/d7slider/default'] = array(
    'title' => t('Sliders'),
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  
  /*$items['admin/config/karbunkul/d7slider/add'] = array(
    'title' => t('Add'),
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('d7slider_newslider_form'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );*/
  
  $items['admin/config/karbunkul/d7slider/settings'] = array(
    'title' => 'Settings',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('d7slider_settings_form'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  
  $items['admin/config/karbunkul/d7slider/templates'] = array(
    'title' => t('Templates'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => TRUE,
    'weight' => 20,
  );
  
  return $items;
}

function d7slider_settings_form($form){
  $templates = array();
  // выбор шаблона
  $templates = db_query('select tid, title from {d7slider_templates}')->fetchAllKeyed();
  
  $form['template'] = array(
    '#type' => 'select',
    '#title' => t('Default template'),
    '#description' => t('Default templates for new slider'),
    '#options' => $templates,
    '#default_value' => variable_get('d7slider_global_template', 'empty'),
  );
  // выбор слайдера
  $sliders = array();
  $sliders = db_query('select sid, title from {d7slider_sliders}')->fetchAllKeyed();
  
  $form['slider'] = array(
    '#type' => 'select',
    '#title' => t('Default slider'),
    '#description' => t('Show default slider'),
    '#options' => $sliders,
    '#default_value' => variable_get('d7slider_global_slider', 'empty'),
  );
  
  $form = system_settings_form($form);

  return $form;
}

function d7slider_settings_form_validate($form, $state){
  $template = $state['input']['template'];
  $slider = $state['input']['slider'];
  
  if ( $template == 'empty' ){
    form_set_error('template', 'необходимо выбрать шаблон');
  }else{
    variable_set('d7slider_global_template', $template);
  }
}

function d7slider_newslider_form($form, $state){
  // режим редактирования или добавления
  $mode = 'new';
  if ( arg(5) != '' ) {
    $mode = arg(5);
  }
  
  if ( $mode == 'new' ){
    $form['common'] = array(
      '#type' => 'fieldset', 
      '#title' => t('Add new slider'), 
      '#weight' => 0, 
      '#collapsible' => FALSE, 
      '#collapsed' => FALSE,
    );
    // заголовок слайдера
    $form['common']['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#required' => TRUE,
      //'#default_value' => '123',
      '#description' => 'Input slider title',
    );
    // выбор шаблона
    $templates = db_select('d7slider_templates', 't')->fields('t',array('tid','title'))->execute()->fetchAllAssoc('tid');
    
    $items = array();
    foreach ($templates as $row) {
      $items[$row->tid] = $row->title;
    }
    
    $form['common']['template'] = array(
      '#type' => 'select',
      '#title' => 'Template',
      '#required' => true,
      '#options' => $items,
      '#default_value' => variable_get('d7slider_global_template', 'empty'),
    );
    
    $form['common']['description'] = array(
      '#type' => 'textarea',
      '#title' => t('Description'),
      '#rows' => 3,
      '#cols' => 30,
    );
  }
  
    
  
  // группировка полей
  
  
  $form = system_settings_form($form);
  $form['#submit'] = array('d7slider_newslider_form_submit');
 
  $form['actions']['submit']['#mode'] = 'edit';
  if ( $mode == 'edit' ){
    $form['actions']['submit']['#value'] = t('Save changes');
    
    $form['actions']['cancel'] = array(
      '#type' => 'button',
      '#value' => t('Cancel'),
      '#executes_submit_callback' => TRUE,
      '#submit' => array('d7slider_newslider_form_cancel'),
      
    );
  }else{
    $form['actions']['submit']['#value'] = t('Add new slider');
    
  }
  return $form;
}

function d7slider_newslider_form_cancel(){
  drupal_goto('admin/config/karbunkul/d7slider');
}

function d7slider_newslider_form_validate($form, $state){
  //dsm($state);
}

function d7slider_newslider_form_submit($form, &$state){
 $slider = array(
  'title' => $state['input']['title'],
  'tid' => $state['input']['template'],
  'created' => REQUEST_TIME,
  'settings' => '0',
  'weight' => 0,
 );
 $rec = db_insert('d7slider_sliders')->fields($slider)->execute();
 //dsm($state);
}

function d7slider_editslider_form($form){
  $form['title'] = array(
    '#type' => 'textfield',
    
  );
  
  return $form;
}

function page_sliders(){
  // форма добавления нового слайдера
  $out['new_slider'] = array(
    drupal_get_form('d7slider_newslider_form'),
  );
  // заголовок таблицы
  $header = array(t('Title'), t('Template'), t('Actions'));
  // данные из бд
  $items = array();
  $rows = db_select('d7slider_sliders', 's')->fields('s', array('sid', 'title', 'tid'))->execute()->fetchAll();
  foreach ($rows as $row) {
    $path = '/admin/config/karbunkul/d7slider/';
    $actions = array(
      'edit' => l(t('Edit'), $path . $row->sid . '/edit'),
      'delete' => l(t('Delete'), $path . $row->sid . '/delete'),
    );
    
    $items[] = array($row->title, $row->tid, implode($actions, ' '));
  }
  
  $out['table'] = array(
    '#type' => 'markup',
    '#markup' => theme('table', array('header' => $header, 'rows' => $items )),
    '#empty' => t('Your table is empty'),
  );
  return $out;
}